server:
  port: 8081
  servlet:
    context-path: /recruit

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.59.21/recruit?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root

  rabbitmq:
    host: 8.131.59.21
    port: 5672
    username: root
    password: root
    listener:
      direct:
        prefetch: 1
#    publisher-confirm-type: correlated
#    publisher-returns: true