server:
  port: 8081
  servlet:
    context-path: /recruit

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.131.59.21/recruit?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root

  rabbitmq:
    host: 119.23.53.104
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        prefetch: 1
      type: simple
      simple:
        default-requeue-rejected: false
        acknowledge-mode: manual

  #    publisher-confirm-type: correlated
#    publisher-returns: true

  redis:
    database: 0
    host: 8.131.59.21
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 1
    timeout: 3000

