server:
  port: 8081
  servlet:
    context-path: /recruit

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/recruit?characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root